name: Trigger auto deployment for ai-demos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ai-demos-AutoDeployTrigger-5d84daca-3ded-4a58-9f0f-91caed38675a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AIDEMOS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AIDEMOS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AIDEMOS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/webapp
          dockerfilePath: Dockerfile
          registryUrl: ${{ secrets.AIDEMOS_REGISTRY_URL }}
          registryUsername: ${{ secrets.AIDEMOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AIDEMOS_REGISTRY_PASSWORD }}
          containerAppName: ai-demos
          resourceGroup: aarch-dev-rg
          imageToBuild: default/ai-demos:${{ github.sha }}


